# Generated by Django 4.2.1 on 2023-05-20 08:22

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('type_Icecream', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('work', models.BooleanField(default=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), bboard.models.my_validator])),
            ],
        ),
        migrations.CreateModel(
            name='IcecreamMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_building', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('ice_creams', models.ManyToManyField(to='bboard.icecream')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('study', models.BooleanField(default=True)),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.person')),
            ],
        ),
    ]
